### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by zhibotian** [xiaoyao3302/CCVC#1]
Hi, thanks for your good work, I have a question is  why the CPS result for Cityscapes dataset is not mentioned in your Table3 ?

**Comment by xiaoyao3302** [comment]
Thanks for your attention, we follow the split protocol used in [41, 43] on Cityscapes, while CPS uses a different protocol and therefore was not included in Table 3. We have supplemented the corresponding experiments during the rebuttal, and we will update our results in the camera-ready version.
________________________________
发件人: Zhibo Tian ***@***.***>
发送时间: 2023年3月6日 18:26
收件人: xiaoyao3302/CCVC ***@***.***>
抄送: Subscribed ***@***.***>
主题: [xiaoyao3302/CCVC] Results (Issue #1)


Hi, thanks for your good work, I have a question is why the CPS result for Cityscapes dataset is not method in you Table3 ?

―

**Comment by zhibotian** [comment]
Thanks for your reply, actually the [41,43] is also follow the CPS data spilt. I'm looking forward to seeing the camera-ready version.
