### ISSUE TITLE
About unlabeled.txt

### ISSUE THREAD

**Issue by Question11** [xiaoyao3302/CCVC#10]
Excuse me, why does your unlabeled. txt file also have a mask image location corresponding to each unlabeled data？If I have a new batch of unlabeled data without corresponding mask images, how should I edit the unlabeled. txt file？

**Comment by xiaoyao3302** [comment]
Hi, please refer to line 66 in aug_semi.py. As we only need to use ignore_mask to prevent ambiguity, you might use any txt files and you only need to make sure the ignore_mask is what you desire. You can probably try to set the ignore_mask as all 0.

**Comment by Question11** [comment]
> Hi, please refer to line 66 in aug_semi.py. As we only need to use ignore_mask to prevent ambiguity, you might use any txt files and you only need to make sure the ignore_mask is what you desire. You can probably try to set the ignore_mask as all 0.

Hi, thank you for your reply. Your reply has been very helpful to me. May God bless you.

**Comment by xiaoyao3302** [comment]
Thanks, and may the Force be with you.
