### ISSUE TITLE
Question about the CPL loss

### ISSUE THREAD

**Issue by Hugo-cell111** [xiaoyao3302/CCVC#11]
Hi! After reading your paper, I think your CPL loss is basically the same as the one in CPS. However, you assign a bigger weight wc to the conflict area where one of the subnets are confident of its prediction. But I am not sure whether what I think is right or not. Thanks!

**Comment by xiaoyao3302** [comment]
Yes, you are right

**Comment by Hugo-cell111** [comment]
Thanks!
