### ISSUE TITLE
关于子网坍缩

### ISSUE THREAD

**Issue by Inev777** [xiaoyao3302/CCVC#12]
Hi！您好，您的工作非常出色和有效，但我在多次实验后有这么几个问题。我发现如果去掉loss_cosine，似乎在有标签数据越少的时候，子网越容易坍缩，从而导致性能很差，差不多跑三次就会有一次坍缩，导致效果差，但也不是每次都坍缩，可能这是与网络的随机初始化有关。在有标签越多的情况下，往往不是那么容易坍缩。我能理解这种现象是因为，有标签越多的情况下，学习到了更多的准确的语义信息，这样决策边界和预测会更加多样，从而子网越不容易坍缩。而loss_cosine则保证了下限，加上之后不管结果如何波动，都在可控范围之内，而不会出现很差很差的性能。请问我的理解是正确的吗，非常期待您的回复与指导交流

**Comment by xiaoyao3302** [comment]
hello 感谢您的关注，我是这么理解这个问题的，我觉得其实可以把label的数量和网络塌陷分开理解，就是假设极端情况没有label，这时候很容易导致平凡解，有label的时候会避免这个现象的出现，同时label越多，对语义的学历能力越强，但是这对模型的塌陷没有太大的影响，因为两只网络的输入和预训练模型都是一样的（如果不是随机初始化的话），再加上监督信号很有可能也是一样的，所以两只网络很容易塌陷。我们的cosine loss只是为了防止两只网络塌陷，强行使两只网络不一致，这样随着训练的进行会因为可以从不同角度去理解所以导致对语义的理解慢慢变好，在有的情况下其实单用这么一个loss的话甚至可能会影响性能（所以才需要CPL），所以我们的这个loss的设计初衷也没有想从提高性能的角度出发。我个人的理解是把性能和塌陷两件事情分开理解，不知道您是否认同？

**Comment by Inev777** [comment]
我明白了，协同训练这种框架能带来性能的提升，但也有缺点，cps
采用的不同的网络初始化，并不能有效避免坍塌，网络初始化权重比较接近的情况下，仍然会导致网络坍塌，loss_cosine是为了避免这种情况的发生，即使有时候会影响一点点性能，但也是必要的，保证了训练的稳定性。我能理解了，非常感谢您的工作，给了我很大的启发，祝大佬科研顺利！

Edmond Skywalker ***@***.***>于2024年3月6日 周三19:30写道：

**Comment by xiaoyao3302** [comment]
大佬加油！
