### ISSUE TITLE
Confusion about Equations

### ISSUE THREAD

**Issue by Ming-er** [xiaoyao3302/CCVC#2]
Sorry to bother you. Is there something wrong in Eq.4, 6, 7? If not, could you please give me some intuitions about these expressions?

**Comment by xiaoyao3302** [comment]
Dear Yiming,

Thanks for your attention and thanks for pointing it out. I'm sorry for the mistake, as we use the cross-supervision, Eq. 4 should be written as:

\mathcal{L}_{con,i}^u = \frac{1}{N} \sum_{m=1}^{N} \frac{1}{W \times H} \sum_{n=0}^{W \times H} \ell_{ce}(\widetilde{y}_{mn,i}^{u}, \hat{y}_{mn,(3-i)}^{u})

where i equals 1 or 2, indicating the first or the second sub-net. Note that when i equals 1, (3-i) equals to 2, and vice versa. The same modification should be made in Eq. 6 and 7.

If you have any other questions, please feel free to ask.

Best wishes,
Zicheng
________________________________
发件人: Yiming Li ***@***.***>
发送时间: 2023年3月14日 22:04
收件人: xiaoyao3302/CCVC ***@***.***>
抄送: Subscribed ***@***.***>
主题: [xiaoyao3302/CCVC] Confusion about Equations (Issue #2)


Sorry to bother you. Is there something wrong in Eq.4, 6, 7? If not, could you please give me some intuitions about these expressions?

―

**Comment by Ming-er** [comment]
Thanks for your reply! Really nice work!

**Comment by xiaoyao3302** [comment]
Thank you!
________________________________
发件人: Yiming Li ***@***.***>
发送时间: 2023年3月15日 9:38
收件人: xiaoyao3302/CCVC ***@***.***>
抄送: xiaoyao3302 ***@***.***>; Comment ***@***.***>
主题: Re: [xiaoyao3302/CCVC] Confusion about Equations (Issue #2)


Thanks for your reply! Really nice work!

―
