### ISSUE TITLE
Questions about retraining

### ISSUE THREAD

**Issue by RYHSmmc** [xiaoyao3302/CCVC#3]

**Comment by RYHSmmc** [comment]
Hi, when I retrain the CCVC using the script(./tools/train.sh) on cityscapes, should I revise the settings like lr or loss weight？

**Comment by xiaoyao3302** [comment]
Hi, sorry for the delay, of course, you can directly run the script, but note that I set the conf_threshold as 0.2 to reproduce the attached logger result (to see the mask percentage), while setting the threshold to 0.2 or 0 will not have much impact on the performance. Moreover, we did not adjust the parameters carefully, and you can try other weights (w_CE, w_con and w_dis) to get better performance. However, to ensure the cut mix operation works, please set the batch size to 2 at least.
________________________________
发件人: RYHSmmc ***@***.***>
发送时间: 2023年4月3日 10:02
收件人: xiaoyao3302/CCVC ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [xiaoyao3302/CCVC] Questions about retraining (Issue #3)


Hi, when I retrain the CCVC using the script(./tools/train.sh) on cityscapes, should I revise the settings like lr or loss weight？

―

**Comment by W-Kinlon** [comment]
Hi, I want to use CVCC to train my own dataset and obtain my own set of metrics. Could you provide a simplified version of the network that only requires input of size and segmentation type?

**Comment by xiaoyao3302** [comment]
Hi, I'm confused about your question. Our model has only one input, which is the image, e.g., line 51 in the deeplabv3plus.py file, I'm not sure about the meaning of the segmentation type you mentioned, maybe you can run our code and change the network according to your needs.
