### ISSUE TITLE
Question about the inplanes of ResNet

### ISSUE THREAD

**Issue by Hugo-cell111** [xiaoyao3302/CCVC#5]
Hi! The parameter "inplanes" is set as 128 in https://github.com/xiaoyao3302/CCVC/blob/master/model/backbone/resnet.py#L70, but in the original setting, it should be set as 64. I wonder why the difference exists. Thanks!

**Comment by xiaoyao3302** [comment]
Hi, well actually I used the codebase of UniMatch and I ignored the detailed settings of the backbone model, please refer to https://github.com/LiheYoung/UniMatch for more details.
