### ISSUE TITLE
Question about the setting in your experiment

### ISSUE THREAD

**Issue by Hugo-cell111** [xiaoyao3302/CCVC#6]
Hi! I have some doubt in your code~
1) In your code, the dilation in the experiment of Cityscapes is set as [12,24,36] and the replace_stride_with_dilation is [False, True, True], while other baselines set them as [6,12,18] and the replace_stride_with_dilation: [False, False, True]. So I wonder whether it will affect the results or not?
2) In your paper, the batch size of Cityscapes and Pascal are 8 and 24, respectively. But since you adopt the code of UniMatch, to the Cityscapes, I think the actual bs is 2 * 4(unlabeled images) + 2 * 4(labeled images) = 16, where 4 is the number of GPUs and 2 is the number of images per GPU. So I think the illustration of your paper is a little misleading~ How do you think?
3) Is the output_stride set as 16 in your ResNet backbone? 
Thanks a lot!

**Comment by xiaoyao3302** [comment]
Hi,
1 & 3. The experimental settings of our backbone are consistent with UniMatch, maybe you can change the dilation settings and carry on some experiments. Unfortunately, we did not perform such experiments before.
2. Yes, there are 2 labeled and 2 unlabeled data on one GPU and there are 4 GPUs in total.

**Comment by Hugo-cell111** [comment]
Thanks for your answer! In question 1 I mean the dilation in the [code](https://github.com/xiaoyao3302/CCVC/blob/master/configs/cityscapes.yaml) of Cityscapes is set as [12,24,36] and the replace_stride_with_dilation is [False, True, True], which are not consistent with UniMatch. So I don't know whether it is the final setting of your experiment.

**Comment by xiaoyao3302** [comment]
Ah, I see, UniMatch modifies the settings, I adopt the dilation settings from the last version of UniMatch. Yes, This is the final setting of my experiment ([False, True, True]).

**Comment by Hugo-cell111** [comment]
Get it. Thanks!
