### ISSUE TITLE
Question about the evaluation method

### ISSUE THREAD

**Issue by Hugo-cell111** [xiaoyao3302/CCVC#9]
Hi! In this line of [code](https://github.com/xiaoyao3302/CCVC/blob/master/CCVC_aug.py#L505C13-L505C88), "center_crop" is adopted when training with evaluation. I know it is for speeding up the whole training process, but I wonder if there is difference between center_crop or sliding windows, and how large the difference is. Thanks!

**Comment by xiaoyao3302** [comment]
Yeah, the results of sliding window on CityScapes are usually two points better than that of center crop.
